# Generated by Django 5.0.7 on 2025-09-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_ready",
            field=models.BooleanField(default=False),
        ),
    ]
