# Generated by Django 5.0.7 on 2025-09-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_player_is_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="rules_options",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
