# Generated by Django 5.0.7 on 2026-07-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_backfill_userprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_type',
            field=models.CharField(choices=[('bataille_corse', 'Bataille Corse')], default='bataille_corse', max_length=50),
        ),
    ]
