# Generated by Django 5.0.7 on 2026-07-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_room_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_selected',
            field=models.BooleanField(default=False),
        ),
    ]
