# Generated by Django 5.0.7 on 2026-07-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_room_game_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='game_type',
            field=models.CharField(choices=[('bataille_corse', 'Bataille Corse'), ('1_percent', 'Le 1%')], default='bataille_corse', max_length=50),
        ),
    ]
